import type { Metadata } from 'next';

import './globals.css';
import { wantedSans } from '@/shared/assets/fonts';
import { Providers } from '@/shared/providers';
import { Toaster } from '@/shared/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${wantedSans.variable} overflow-y-scroll bg-background text-white font-wanted-sans antialiased`}
      >
        <div className="relative mx-auto min-h-screen max-w-xl">
          <Providers>{children}</Providers>
        </div>
        <Toaster
          position="bottom-center"
          offset={{ bottom: 60, left: 24, right: 24 }}
          mobileOffset={{ bottom: 60, left: 24, right: 24 }}
        />
      </body>
    </html>
  );
}
